### ISSUE TITLE
WSL is not necessarilly Ubuntu

### ISSUE THREAD

**Issue by kitlith** [talon/bin#1]
https://github.com/talon/bin/blob/a43c287e7386ab01d855e6c0dd8c5750c580c517/src/core.sh#L36

https://github.com/talon/bin/blob/a43c287e7386ab01d855e6c0dd8c5750c580c517/src/core.sh#L43

WSL is not guaranteed to be Ubuntu (or, more specifically, have APT installed), and can also be Arch, for example.

**Comment by talon** [comment]
I added $DISTRO instead!
